// Frontend estático: todo se carga desde autos-data.json
const GASTOS_POR_PROVINCIA={cordoba:500000,santiago:600000};
const COEF={12:85.8,24:42.9,36:28.6,48:21.45,60:17.16};
const COEF_UVA={24:55.06065,36:41.35006,48:34.64069,60:30.72835};
const TEL="541234567890";
const marcaSelect=document.getElementById("marca"),modeloSelect=document.getElementById("modelo"),
versionSelect=document.getElementById("version"),anioVehiculo=document.getElementById("anioVehiculo"),
montoFinanciar=document.getElementById("montoFinanciar"),mostrarMonto=document.getElementById("mostrarMonto"),
mostrarNeto=document.getElementById("mostrarNeto"),mostrarGastos=document.getElementById("mostrarGastos"),
btnWhatsApp=document.getElementById("btnWhatsApp"),cuotasDiv=document.getElementById("cuotas"),
infoVehiculo=document.getElementById("infoVehiculo"),vehiculoNombre=document.getElementById("vehiculoNombre"),
valorVehiculo=document.getElementById("precioEstimado"),estadoDatos=document.getElementById("estadoDatos");
let datosAutos=null,precioActual=0,vehiculoActual=null;
async function cargarDatosAutos(){try{const r=await fetch("./autos-data.json?cache="+Date.now());if(!r.ok)throw Error("HTTP "+r.status);
datosAutos=await r.json();cargarMarcas();const s=datosAutos.estadisticas||{};
estadoDatos.classList.add("ok");estadoDatos.textContent=`Datos disponibles: ${datosAutos.marcas.length} marcas, ${s.modelos??contarModelos()} modelos y ${s.versionesConValuacion??Object.keys(datosAutos.vehiculos).length} versiones con valuación.`;
}catch(e){console.error(e);estadoDatos.classList.add("error");estadoDatos.textContent="No se pudieron cargar los datos de vehículos.";}}
function contarModelos(){return new Set(Object.values(datosAutos.vehiculos).map(v=>v.marca+"|||"+v.modelo)).size}
function reset(s,t){s.innerHTML=`<option value="">${t}</option>`}
function cargarMarcas(){reset(marcaSelect,"Selecciona una marca...");[...datosAutos.marcas].sort((a,b)=>a.localeCompare(b,"es")).forEach(m=>{let o=document.createElement("option");o.value=m;o.textContent=m;marcaSelect.appendChild(o)});modeloSelect.disabled=versionSelect.disabled=anioVehiculo.disabled=true}
function cargarModelos(){reset(modeloSelect,"Selecciona un modelo...");reset(versionSelect,"Selecciona una versión...");reset(anioVehiculo,"Selecciona un año...");versionSelect.disabled=anioVehiculo.disabled=true;limpiarVehiculo();let m=marcaSelect.value;if(!m){modeloSelect.disabled=true;return}let set=new Set;Object.values(datosAutos.vehiculos).forEach(v=>{if(v.marca===m)set.add(v.modelo)});[...set].sort((a,b)=>a.localeCompare(b,"es")).forEach(x=>{let o=document.createElement("option");o.value=x;o.textContent=x;modeloSelect.appendChild(o)});modeloSelect.disabled=set.size===0}
function cargarVersiones(){reset(versionSelect,"Selecciona una versión...");reset(anioVehiculo,"Selecciona un año...");anioVehiculo.disabled=true;limpiarVehiculo();let m=marcaSelect.value,mo=modeloSelect.value;if(!m||!mo){versionSelect.disabled=true;return}Object.entries(datosAutos.vehiculos).filter(([id,v])=>v.marca===m&&v.modelo===mo).sort((a,b)=>a[1].version.localeCompare(b[1].version,"es")).forEach(([id,v])=>{let o=document.createElement("option");o.value=id;o.textContent=v.version;versionSelect.appendChild(o)});versionSelect.disabled=versionSelect.options.length<=1}
function cargarAnios(){reset(anioVehiculo,"Selecciona un año...");limpiarVehiculo();let v=datosAutos.vehiculos[versionSelect.value];if(!v){anioVehiculo.disabled=true;return}Object.keys(v.precios).map(Number).filter(y=>y>=2013).sort((a,b)=>b-a).forEach(y=>{let o=document.createElement("option");o.value=y;o.textContent=y;anioVehiculo.appendChild(o)});anioVehiculo.disabled=anioVehiculo.options.length<=1}
function obtenerPrecio(){limpiarVehiculo();let v=datosAutos.vehiculos[versionSelect.value],y=anioVehiculo.value;if(!v||!y)return;let p=Number(v.precios[y]);if(!Number.isFinite(p)||p<=0)return;precioActual=p;vehiculoActual=v;valorVehiculo.textContent="$"+p.toLocaleString("es-AR");vehiculoNombre.textContent=`${v.marca} ${v.modelo} ${v.version} (${y})`;document.getElementById("precioFuente").textContent="Valuación en pesos argentinos. Datos de Arg Autos.";infoVehiculo.style.display="block";calcularPrestamo()}
function limpiarVehiculo(){precioActual=0;vehiculoActual=null;infoVehiculo.style.display="none";document.getElementById("montoMaximoTradicional").textContent="$0";document.getElementById("montoMaximoUVA").textContent="$0";document.getElementById("textoPorcentajeTradicional").textContent="";document.getElementById("textoPorcentajeUVA").textContent=""}
function calcularPrestamo(){if(!precioActual)return;let y=Number(anioVehiculo.value),p=y>=2025?80:y>=2021?70:y>=2016?60:y>=2013?50:0;document.getElementById("montoMaximoTradicional").textContent="$"+Math.floor(precioActual*p/100/1000)*1000 .toLocaleString("es-AR");document.getElementById("textoPorcentajeTradicional").textContent=p+"%";let pu=y>=2023?60:y>=2021?50:0,mu=pu?Math.floor(precioActual*pu/100/1000)*1000:0;let e=document.getElementById("montoMaximoUVA");e.textContent=mu?"$"+mu.toLocaleString("es-AR"):"No disponible para este año.";document.getElementById("textoPorcentajeUVA").textContent=pu?pu+"%":"";montoFinanciar.value=Math.floor(precioActual*p/100/1000)*1000;calcularTodo()}
function calcularTodo(){let m=Number(montoFinanciar.value)||0,p=document.getElementById("provincia").value,g=GASTOS_POR_PROVINCIA[p]||0,n=m-g;mostrarMonto.textContent="$"+m.toLocaleString("es-AR");mostrarNeto.textContent=n>0?"$"+n.toLocaleString("es-AR"):"Monto insuficiente";mostrarGastos.textContent="$"+g.toLocaleString("es-AR");cuotasDiv.innerHTML="";for(const x in COEF){let c=Math.round(m*COEF[x]/1000),t=c*Number(x);cuotasDiv.innerHTML+=`<div class="card card-cuota"><div class="meses">${x} meses</div><div class="cuota">$${c.toLocaleString("es-AR")}</div><div class="total">Total: $${t.toLocaleString("es-AR")}</div><div class="coef">Coeficiente: ${COEF[x]}</div></div>`}calcularUVA()}
function calcularUVA(){let m=Number(montoFinanciar.value)||0;for(const p in COEF_UVA){let e=document.getElementById("uva"+p);if(e)e.textContent="$"+Math.round(m/1000*COEF_UVA[p]).toLocaleString("es-AR")}}
marcaSelect.addEventListener("change",cargarModelos);modeloSelect.addEventListener("change",cargarVersiones);versionSelect.addEventListener("change",cargarAnios);anioVehiculo.addEventListener("change",obtenerPrecio);montoFinanciar.addEventListener("input",calcularTodo);document.getElementById("provincia").addEventListener("change",calcularTodo);btnWhatsApp.addEventListener("click",()=>{if(window.textoWA)window.open("https://wa.me/"+TEL+"?text="+window.textoWA)});window.addEventListener("load",()=>{cargarDatosAutos();calcularTodo()});
